# dvc.yaml
stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    - params.yaml
    params:
    - data_ingestion
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - params.yaml
    - data/interim
    params:
    - feature_engineering
    outs:
    - data/processed

  model_building:
    cmd: python src/model_building.py
    deps:
    - src/model_building.py
    - params.yaml
    - data/processed
    params:
    - model_building
    outs:
    - models

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - models/model.pkl
    - data/processed
    metrics:
    - reports/metrics.json:
        cache: false
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
