# Global parameters for all stages
data_ingestion:
  test_size: 0.2          # Train/test split ratio
  data_url: https://raw.githubusercontent.com/vikashishere/Datasets/main/spam.csv

feature_engineering:
  max_features: 5000      # TF-IDF vectorizer configuration

model_building:
  n_estimators: 200       # RandomForest hyperparameters
  random_state: 42

model_evaluation:
  metrics:                # Thresholds for monitoring
    target_accuracy: 0.95
    target_precision: 0.9
